import React, { useEffect } from 'react';
import { Navbar } from '../components/Navbar';
import { Footer } from '../components/Footer';
import { AlertTriangle, ShieldCheck, Mail, CheckCircle2 } from 'lucide-react';

export const Disclaimer: React.FC = () => {
  useEffect(() => {
    document.title = 'Disclaimer — ONCEClic';
  }, []);

  return (
    <div className="min-h-screen bg-slate-950 text-slate-100 flex flex-col selection:bg-emerald-500 selection:text-slate-950">
      <Navbar />

      <main className="flex-1 py-16 px-4 sm:px-6 lg:px-8 max-w-4xl mx-auto w-full">
        <div className="mb-10 pb-6 border-b border-slate-800">
          <div className="inline-flex items-center space-x-2 px-3 py-1 rounded-full bg-emerald-500/10 border border-emerald-500/20 text-emerald-400 text-xs font-semibold uppercase tracking-wider mb-4">
            <AlertTriangle className="w-3.5 h-3.5" />
            <span>Service Advisory</span>
          </div>
          <h1 className="text-3xl sm:text-4xl font-black text-white tracking-tight">
            Legal & AI Output Disclaimer
          </h1>
          <p className="text-xs sm:text-sm text-slate-400 mt-2">
            Last Updated: September 2026 &bull; Service: ONCEClic (onceclic.com)
          </p>
        </div>

        <div className="space-y-8 text-sm text-slate-300 leading-relaxed">
          {/* Section 1 */}
          <section className="bg-slate-900 border border-slate-800 rounded-2xl p-6 sm:p-8 space-y-4">
            <h2 className="text-lg font-bold text-white">1. Software & Automation Tool</h2>
            <p>
              <strong>ONCEClic</strong> provides software tools and artificial intelligence automation designed to assist businesses with customer communication, initial inquiry triage, and calendar appointment scheduling.
            </p>
          </section>

          {/* Section 2 */}
          <section className="bg-slate-900 border border-amber-500/30 rounded-2xl p-6 sm:p-8 space-y-4">
            <h2 className="text-lg font-bold text-white">2. No Professional, Legal, Medical, or Financial Advice</h2>
            <p>
              The outputs, responses, messages, and suggestions generated by ONCEClic and its AI receptionists do <strong>not</strong> constitute:
            </p>
            <ul className="list-disc pl-5 space-y-2 text-xs sm:text-sm text-slate-300">
              <li><strong>Legal Advice:</strong> No information provided by the software creates an attorney-client relationship or constitutes legal counsel.</li>
              <li><strong>Medical or Healthcare Advice:</strong> The software is not a medical device, diagnosis tool, or emergency triage service. Patients seeking urgent medical care should always contact emergency services directly.</li>
              <li><strong>Financial or Tax Advice:</strong> Automated replies or pricing estimates do not constitute certified accounting, financial planning, or tax advisory services.</li>
              <li><strong>Certified Professional Services:</strong> Any specific professional determinations must be performed by licensed human professionals.</li>
            </ul>
          </section>

          {/* Section 3 */}
          <section className="bg-slate-900 border border-slate-800 rounded-2xl p-6 sm:p-8 space-y-4">
            <h2 className="text-lg font-bold text-white">3. Review and Verification of AI Outputs</h2>
            <p>
              Because artificial intelligence systems may occasionally produce inaccuracies or misinterpret nuanced queries, business owners and authorized team members are advised to periodically review automated conversational logs, email responses, and appointment confirmations.
            </p>
            <p>
              The accuracy of your AI receptionist depends directly on the completeness and accuracy of the business knowledge base, services, and FAQ content you configure.
            </p>
          </section>

          {/* Section 4 */}
          <section className="bg-slate-900 border border-emerald-500/20 rounded-2xl p-6 sm:p-8 space-y-4">
            <h2 className="text-lg font-bold text-white flex items-center space-x-2">
              <Mail className="w-5 h-5 text-emerald-400" />
              <span>4. Inquiries & Support</span>
            </h2>
            <p>
              If you have any questions regarding this disclaimer, please contact us at:
            </p>
            <div className="bg-slate-950 border border-slate-800 rounded-xl p-4 text-xs font-mono">
              <span className="text-slate-400">Email: </span>
              <a href="mailto:kamiabc007@gmail.com" className="text-emerald-400 hover:underline font-bold">
                kamiabc007@gmail.com
              </a>
            </div>
          </section>
        </div>
      </main>

      <Footer />
    </div>
  );
};
